---
- name: provision packages
  hosts: webserver
  
  become: yes
  tasks:

  - name: update cache # sudo yum update
    ansible.builtin.yum:
        update_cache: yes
    when: ansible_distribution == "Amazon" #Run this task only if the distribution is Amazon Linux.

  # Install Docker
  - name: install prerequisites # sudo yum install docker
    ansible.builtin.yum:
      name:
        - docker
      update_cache: yes

  - name: add user permissions # Add sudo user to docker group
    shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

  - name: Reset ssh connection for changes to take effect
    meta: "reset_connection"

  # Install Docker SDK
  - name: install python package manager
    ansible.builtin.yum:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{ ansible_env.SUDO_USER }}"
    pip:
      executable: /usr/bin/pip3
      name:
        - docker
        - docker-compose

  - name: Install requests lib 
    pip:
      executable: /usr/bin/pip3
      name: requests==2.28.2
      state: present

  - name: Install docker-py
    pip:
      executable: /usr/bin/pip3
      name: docker-py
      state: present

################

- name: Start app
  hosts: all
  become: yes

  
  tasks:
  - name: Start docker
    service:
      name: docker
      state: started

  - name: Run container

    community.docker.docker_container:
      name: app-container
      state: started
      image: "sdupegui/planet-app-linux:1.3"
      pull: true
      ports:

        - "5000:5000"

