- hosts: all
  become: true

  tasks:
  #   - name: log into docker hub registry
  #     docker_login:
  #       email: "your-email@address"
  #       username: "a-dockerhub-username"
  #       password: "a-dockerhub-password"

    - name: ensure a container is running
      docker_container:
        name: app-container
        state: started
        image: "sdupegui/planet-app-linux:1.3"
        pull: true
        ports:
          - "5000:5000"
